
services:
  php-unit:
    build:
      context: .
      args:
        UID: ${DUID:-1000}
        GID: ${DGID:-1000}
      dockerfile: docker/${APP_ENV}/Dockerfile
    container_name: php-unit
    environment:
      APP_ENV: ${APP_ENV}
      COMPOSER_MEMORY_LIMIT: -1
      COMPOSER_ALLOW_SUPERUSER: 1
    ports:
      - "80:80"
    volumes:
      - .:/app:rw
      - ./unit-config.json:/docker-entrypoint.d/config.json:ro
    depends_on:
      - db_unit
    networks:
      - unit_network

  db_unit:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    ports:
      - 5432:5432
    volumes:
      - db_unit:/var/lib/postgresql/data:rw
      - ./docker/db_unit:/docker-entrypoint-database.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_unit: ~


networks:
  unit_network:
    driver: bridge
